"""
Loads Aang GBA sprite strips, slices them into frames, and scales them
to match the game's player dimensions.
"""

import pygame

SHEET_PATH       = "Game Boy Advance - Avatar_ The Last Airbender - Playable Characters - Avatar Aang.png"
DRAKE_SHEET_PATH = "NES - Sword Master - Enemies & Bosses - Fire Drake.png"
BG       = (255, 255, 255)
BG_BLACK = (0,   0,   0)

# (x, y, w, h, expected_frame_count)
_STRIPS = {
    "walk_r":  (4,   19,  197, 37,  8),
    "idle":    (246, 602, 184, 66,  5),
    "scoot_r": (421, 508, 244, 76,  5),
    "blast":   (166, 998, 247, 35,  5),
    "glide":   (559,  16, 158, 55,  4),
    "appa":    (299,  19, 219, 119, 1),
}

_TARGET_H = 40   # scale all Aang frames to this pixel height


def _col_density(surface, col: int) -> int:
    h = surface.get_height()
    cnt = 0
    for row in range(h):
        r, g, b, *_ = surface.get_at((col, row))
        if not (r >= 245 and g >= 245 and b >= 245):
            cnt += 1
    return cnt


def _auto_slice(surface, gap_thresh: int = 2, min_fw: int = 10) -> list:
    """Find frames by locating gap columns (density <= gap_thresh)."""
    w    = surface.get_width()
    dens = [_col_density(surface, c) for c in range(w)]
    in_frame    = False
    frame_start = 0
    frames      = []
    for col, d in enumerate(dens):
        if d > gap_thresh and not in_frame:
            in_frame    = True
            frame_start = col
        elif d <= gap_thresh and in_frame:
            in_frame = False
            if col - frame_start >= min_fw:
                frames.append(surface.subsurface(
                    (frame_start, 0, col - frame_start, surface.get_height())).copy())
    if in_frame and w - frame_start >= min_fw:
        frames.append(surface.subsurface(
            (frame_start, 0, w - frame_start, surface.get_height())).copy())
    return frames


def _even_slice(surface, n: int) -> list:
    """Divide strip into n equal-width frames."""
    w = surface.get_width()
    fw = w // n
    return [surface.subsurface((i * fw, 0, fw, surface.get_height())).copy()
            for i in range(n)]


def _slice_strip(surface, expected_n: int) -> list:
    """Try auto-detect; fall back to even-divide if count doesn't match hint."""
    frames = _auto_slice(surface)
    if len(frames) == expected_n:
        return frames
    # Try slightly looser threshold
    frames = _auto_slice(surface, gap_thresh=4, min_fw=12)
    if len(frames) == expected_n:
        return frames
    # Fall back to even division
    return _even_slice(surface, expected_n)


def _scale_frame(surf: pygame.Surface, target_h: int) -> pygame.Surface:
    w, h = surf.get_size()
    new_w = max(1, round(w * target_h / h))
    scaled = pygame.transform.scale(surf, (new_w, target_h))
    scaled.set_colorkey(BG)
    return scaled


def load() -> dict:
    """
    Returns dict of animation_name -> [pygame.Surface, ...]

    Keys: walk_r, walk_l, idle, scoot_r, scoot_l, blast, glide, appa
    walk_l and scoot_l are generated by horizontally flipping their
    right-facing counterparts.
    Returns {} if the sheet file is missing.
    """
    try:
        sheet = pygame.image.load(SHEET_PATH).convert()
    except Exception:
        return {}

    result = {}

    for name, (sx, sy, sw, sh, n) in _STRIPS.items():
        strip = sheet.subsurface((sx, sy, sw, sh)).copy()
        strip.set_colorkey(BG)

        if name == "appa":
            scaled = pygame.transform.scale(strip, (round(sw * 60 / sh), 60))
            scaled.set_colorkey(BG)
            result["appa"] = [scaled]
        else:
            frames = _slice_strip(strip, n)
            result[name] = [_scale_frame(f, _TARGET_H) for f in frames]

    # Generate mirrored left-facing variants
    def flip_frames(frames):
        return [pygame.transform.flip(f, True, False) for f in frames]

    if "walk_r" in result:
        result["walk_l"] = flip_frames(result["walk_r"])
    if "scoot_r" in result:
        result["scoot_l"] = flip_frames(result["scoot_r"])

    return result


def load_drake() -> dict:
    """
    Returns {
      "enemy":    [Surface, Surface],  # tall flame, 2-frame flicker
      "fireball": [Surface, Surface],  # horizontal fireball, 2-frame anim
    }
    Returns {} on failure.
    """
    try:
        sheet = pygame.image.load(DRAKE_SHEET_PATH).convert()
    except Exception:
        return {}

    # Manually mapped bounding boxes from NES sprite sheet
    # (x, y, w, h) — black (0,0,0) background
    crops = {
        "flame_tall":  (35, 32, 18, 39),   # standing flame — enemy body
        "fireball_a":  (4,  4,  16, 16),   # flying fireball frame A
        "fireball_b":  (24, 4,  16, 15),   # flying fireball frame B
    }

    def extract(x, y, w, h, target_h):
        sub = sheet.subsurface((x, y, w, h)).copy()
        sub.set_colorkey(BG_BLACK)
        new_w = max(1, round(w * target_h / h))
        scaled = pygame.transform.scale(sub, (new_w, target_h))
        scaled.set_colorkey(BG_BLACK)
        return scaled

    tall  = extract(*crops["flame_tall"], 44)   # ~20x44
    fb_a  = extract(*crops["fireball_a"], 20)   # 20x20
    fb_b  = extract(*crops["fireball_b"], 20)   # 20x20

    # Second enemy frame: horizontally squash the tall flame slightly
    tall2 = pygame.transform.scale(tall, (tall.get_width() - 4, tall.get_height() + 4))
    tall2.set_colorkey(BG_BLACK)

    return {
        "enemy":    [tall, tall2],
        "fireball": [fb_a, fb_b],
    }
